### ISSUE TITLE
nimble.biomechanics.OpenSimParser.loadGRF is sensitive to small values in timestamp

### ISSUE THREAD

**Issue by TheOne-1** [keenon/nimblephysics#179]
nimble.biomechanics.OpenSimParser.loadGRF was not working properly with such kind of timestamp:
![image](https://github.com/keenon/nimblephysics/assets/25819605/fc8582ab-7b82-4d63-b0ba-f4a35d3d779c)
If I round the timestamp with 3 digit precision as follows, the function worked properly.
![image](https://github.com/keenon/nimblephysics/assets/25819605/7c320231-1216-4f2a-8e90-f77edfb57128)
[repeat the issue.zip](https://github.com/keenon/nimblephysics/files/11658771/repeat.the.issue.zip)

**Comment by nickbianco** [comment]
@TheOne-1 What exactly is the issue? Does the `loadGRF` call fail, or does it load the data incorrectly?

**Comment by TheOne-1** [comment]
It loaded the data incorrectly. I can't remember very well but it's probably related to the sampling rate, which was not loaded as 200 Hz.

**Comment by keenon** [comment]
I think it's possible that this was fixed in the latest revision of the GRF loader, which now always gets exactly the desired timestamps in the output, even if it has to linearly interpolate between frames.
