### ISSUE TITLE
Skeleton.getAccelerometerReadings not found

### ISSUE THREAD

**Issue by TheOne-1** [keenon/nimblephysics#195]
#### Environment
WSL, py38

#### Current Behavior
Skeleton.getAccelerometerReadings cannot be found after upgrading nimblephysics. Reinstalling the old version didn't work.
![image](https://github.com/keenon/nimblephysics/assets/25819605/dc578e19-88a8-4db6-b8b8-d0ba354d8343)

#### Code to Reproduce
[report_bug.zip](https://github.com/keenon/nimblephysics/files/12421488/report_bug.zip)

**Comment by nickbianco** [comment]
The Python interface for that class [is still in place](https://github.com/keenon/nimblephysics/blob/009d1c666da95578c84f7a008f96b7f6036c7461/python/_nimblephysics/dynamics/Skeleton.cpp#L1148). I'm not sure why the object name ends with 'Skeleto' and not 'Skeleton', might be related.

**Comment by TheOne-1** [comment]
Looks like an environment issue.
