### ISSUE TITLE
ModuleNotFoundError: No module named 'nimblephysics.models'

### ISSUE THREAD

**Issue by Arthur151** [keenon/nimblephysics#32]
Thanks for the great work. 
After installation via pip install, the error occurs while importing nimblephysics

**Comment by keenon** [comment]
That's an interesting error. Thanks for reporting! Do you have a `models` folder inside your `nimblephysics` install?

You can figure out where `nimblephysics` was installed by pip by calling `pip show nimblephysics` on a terminal, and then looking for a line that reads something like `Location: /home/YOUR_USER_NAME/.local/lib/python3.8/site-packages`. Then I'd love to see the results of listing the files in your nimblephysics install directory. To continue my running example, something like `ls /home/YOUR_USER_NAME/.local/lib/python3.8/site-packages/nimblephysics`.

**Comment by keenon** [comment]
Ok actually, I think this is my bad. Sorry everyone! I forgot to add the `models/*` directory to our PyPI bundle, so it may not have been getting shipped. I'm pushing an update through CI, so hopefully in a few hours you should be able to update and everything will be fixed.

**Comment by keenon** [comment]
Ok, I've pushed a fix! 🍾 Go ahead and upgrade to the latest version, and the problem should be fixed: `pip3 install --upgrade nimblephysics`

**Comment by keenon** [comment]
Feel free to reopen this if it's still an issue. I'm going to close this for now.
