### ISSUE TITLE
GPU and batch processing

### ISSUE THREAD

**Issue by zhangy76** [keenon/nimblephysics#84]
Hi,

I wonder if the simulation function "nimble.timestep(world, state, action)" supports batch and GPU processing?

Thanks

**Comment by gonultasbu** [comment]
I have not been able to make it work myself so far.

**Comment by MrWhitezz** [comment]
Hello,

Have you found how to run this function `nimble.timestep()` on GPU? I also want to use cuda to accelerate the computation but failed.

**Comment by baixianger** [comment]
If you want large-scale parallel simulation, I highly recommend Isaac Gym from Nvidia.

**Comment by zhangy76** [comment]
Thanks. Will try. There is a also new library released on CVPR2023 called PyPose.
