### ISSUE TITLE
Wrong interpretation of OpenSim polynomial curves of OpenSim?

### ISSUE THREAD

**Issue by antoinefalisse** [keenon/nimblephysics#98]
I used addBiomechanics to process data with [this model. ](https://github.com/stanfordnmbl/opencap-core/blob/main/opensimPipeline/Models/LaiArnoldModified2017_poly_withArms_weldHand.osim)This model is based on the ragagopal opensim model, but I modified the knee joint definitions to use polynomials instead of SimmSplines. Looking great on the nimble viewer but crap in the OpenSim GUI, suggesting a mismatch between OpenSim and Nimble Physics. When replacing the polynomials with the original SimmSplines, it looks good, confirming the polynomials are the problem and probably wrongly interpreted by Nimble Physics. 

For reference, [here ](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1PolynomialFunction.html#details)is the OpenSim polynomialFunction class. If I were to guess, I would first check if you use the same order for the coefficients. OpenSim uses decreasing order

**Comment by nickbianco** [comment]
Closing since fix implemented with #101.
